apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress 
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:latest

        env:
        - name: WORDPRESS_DATABASE_NAME
          valueFrom: 
            configMapKeyRef:
               name: wordpress-configmap 
               key: db_name

        - name: WORDPRESS_DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
               name: wordpress-configmap 
               key: db_host

        - name: WORDPRESS_DATABASE_USER 
          valueFrom: 
            secretKeyRef:
              name: mysql-credentials
              key: username

        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-credentials
              key: password 
