apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-jegan
      containers:
      - name: mysql
        image: bitnami/mysql:latest

        volumeMounts:
        - name: mysql-storage
          mountPath: /bitnami/mysql/data

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root@123
