apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108 # Replace this IP with your CentOS IP
    path: /var/mysql # Replace this path with /var/userxy folder, xy for user01 will be 01 and 17 for user17, etc.,
