apiVersion: v1
kind: Pod
metadata:
  name: with-required-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: diskType
            operator: In
            values:
            - SSD
  containers:
  - name: node-affinity
    image: bitnami/nginx:latest
