apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  containers:
  - name: node-affinity
    image: bitnami/nginx:latest
  affinity:
      nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
        - matchExpressions:
          - key: diskType
            operator: In
            values:
            - SSD
